# Stage 1: Compile and build angular codebase

# Use official node image as the base image
FROM node:latest as build
# Set the working directory
WORKDIR /app
# Copy other packages in ...
# COPY package*.json ./
# Add the source code to app
COPY . .
# Install all the dependencies
RUN npm install
# Build the application
RUN npm run build

# Stage 2: Serve app with nginx server

# Use official nginx image as the base image
FROM nginx:latest
COPY nginx.conf /etc/nginx/nginx.conf
# Set the working directory to nginx asset directory
WORKDIR /usr/share/nginx/html
# Remove default nginx static assets
RUN rm -rf ./*
# Remove default nginx index page
# RUN rm -rf /usr/share/nginx/html/*
# Copy static assets from builder stage
COPY --from=build /app/dist/hymnal/browser .
# Containers run nginx with global directives and daemon off
# ENTRYPOINT [ "nginx", "-g", "daemon off;" ]

# Copy the build output to replace the default nginx contents
# COPY --from=build /app/dist/hymnal /usr/share/nginx/html/
# Copy custom nginx configuration file into place

# Expose port 80 (default HTTP port)
EXPOSE 80
